### ISSUE TITLE
JsString.replace offers some invalid overloads

### ISSUE THREAD

**Issue by niloc132** [google/elemental2#11]
JsString.replace overloads - half are invalid, or at least confusing since they allow the third argument, but it will be ignored:
 ```
//remove
 @JsOverlay
  public final String replace(RegExp regex, Function str, String flags) {
    return replace(
        Js.<ReplaceRegexUnionType>uncheckedCast(regex),
        Js.<ReplaceStrUnionType>uncheckedCast(str),
        flags);
  }

  @JsOverlay
  public final String replace(RegExp regex, Function str) {
    return replace(
        Js.<ReplaceRegexUnionType>uncheckedCast(regex), Js.<ReplaceStrUnionType>uncheckedCast(str));
  }

//remove
  @JsOverlay
  public final String replace(RegExp regex, ReplaceStrUnionType str, String flags) {
    return replace(Js.<ReplaceRegexUnionType>uncheckedCast(regex), str, flags);
  }

  @JsOverlay
  public final String replace(RegExp regex, ReplaceStrUnionType str) {
    return replace(Js.<ReplaceRegexUnionType>uncheckedCast(regex), str);
  }

//remove
  @JsOverlay
  public final String replace(RegExp regex, String str, String flags) {
    return replace(
        Js.<ReplaceRegexUnionType>uncheckedCast(regex),
        Js.<ReplaceStrUnionType>uncheckedCast(str),
        flags);
  }

  @JsOverlay
  public final String replace(RegExp regex, String str) {
    return replace(
        Js.<ReplaceRegexUnionType>uncheckedCast(regex), Js.<ReplaceStrUnionType>uncheckedCast(str));
  }

//remove
  @JsOverlay
  public final String replace(ReplaceRegexUnionType regex, Function str, String flags) {
    return replace(regex, Js.<ReplaceStrUnionType>uncheckedCast(str), flags);
  }

  @JsOverlay
  public final String replace(ReplaceRegexUnionType regex, Function str) {
    return replace(regex, Js.<ReplaceStrUnionType>uncheckedCast(str));
  }

//remove
  public native String replace(ReplaceRegexUnionType regex, ReplaceStrUnionType str, String flags);

  public native String replace(ReplaceRegexUnionType regex, ReplaceStrUnionType str);

//remove
  @JsOverlay
  public final String replace(ReplaceRegexUnionType regex, String str, String flags) {
    return replace(regex, Js.<ReplaceStrUnionType>uncheckedCast(str), flags);
  }

  @JsOverlay
  public final String replace(ReplaceRegexUnionType regex, String str) {
    return replace(regex, Js.<ReplaceStrUnionType>uncheckedCast(str));
  }

//remove
  @JsOverlay
  public final String replace(String regex, Function str, String flags) {
    return replace(
        Js.<ReplaceRegexUnionType>uncheckedCast(regex),
        Js.<ReplaceStrUnionType>uncheckedCast(str),
        flags);
  }

  @JsOverlay
  public final String replace(String regex, Function str) {
    return replace(
        Js.<ReplaceRegexUnionType>uncheckedCast(regex), Js.<ReplaceStrUnionType>uncheckedCast(str));
  }

//remove
  @JsOverlay
  public final String replace(String regex, ReplaceStrUnionType str, String flags) {
    return replace(Js.<ReplaceRegexUnionType>uncheckedCast(regex), str, flags);
  }

  @JsOverlay
  public final String replace(String regex, ReplaceStrUnionType str) {
    return replace(Js.<ReplaceRegexUnionType>uncheckedCast(regex), str);
  }

//remove
  @JsOverlay
  public final String replace(String regex, String str, String flags) {
    return replace(
        Js.<ReplaceRegexUnionType>uncheckedCast(regex),
        Js.<ReplaceStrUnionType>uncheckedCast(str),
        flags);
  }

  @JsOverlay
  public final String replace(String regex, String str) {
    return replace(
        Js.<ReplaceRegexUnionType>uncheckedCast(regex), Js.<ReplaceStrUnionType>uncheckedCast(str));
  }
```

Example code: `"fooBarBaz".replace(/([a-z])([A-Z])/, '$1-$2', 'g')` does not work (returns "foo-BarBaz", but `"fooBarBaz".replace(/([a-z])([A-Z])/g, '$1-$2')` does work ("foo-Bar-Baz").

From https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace:

> Firefox-specific notes
> - flags was a non standard third argument only available in Gecko : str.replace(regexp|substr, newSubStr|function, flags)
> - Starting with Gecko 27 (Firefox 27 / Thunderbird 27 / SeaMonkey 2.24), this method has been adjusted to conform with the ECMAScript specification. When replace() is called with a global regular expression, the RegExp.lastIndex property (if specified) will be reset to 0 (bug 501739).
> - Starting with Gecko 39 (Firefox 39 / Thunderbird 39 / SeaMonkey 2.36), the non-standard flags argument is deprecated and throws a console warning (bug 1142351).
> - Starting with Gecko 47 (Firefox 47 / Thunderbird 47 / SeaMonkey 2.44), the non-standard flags argument is no longer supported in non-release builds and will soon be removed entirely (bug 1245801).
> - Starting with Gecko 49 (Firefox 49 / Thunderbird 49 / SeaMonkey 2.46), the non-standard flags argument is no longer supported (bug 1108382).

Chrome has apparently never supported it, nor have the other browsers.

---

I would have filed this against closure-compiler (with a patch, removing the arg from their externs file), but for some reason we are patching bugs in those externs here, and I assume there is a reason for that rather than fixing the source.

**Comment by jDramaix** [comment]
Thanks. I'll fix that internally (directly in the extern file if it doesnt break too much code) and then export it here.

**Comment by niloc132** [comment]
Is there a discussion anywhere on what is patched in this project, versus fixed upstream? There are some very odd things in those patches that certainly look like bugs - for example, almost certainly Closure-compiler should never trigger that firefox/jvm bug with an object named `java`, that shouldn't be gwt-specific. The missing window.prototype pieces, and Location itself also strike me as a deficiency in closure - does closure normally just rewrite `window.location.assign`? Or are all of these patches just a stopgap while waiting for these fixes to merge upstream?

**Comment by jDramaix** [comment]
I've fixed the bug internally in the extern file. That should be pushed to the closure-compiler repo very soon.

> Is there a discussion anywhere on what is patched in this project, versus fixed upstream?

We try to fix upstream as much as we can. If for any reasons we cannot do it, we patch the extern file. For each patch we open a bug internally as a reminder for cleaning the extern file in the future. 

>  The missing window.prototype pieces, and Location itself also strike me as a deficiency in closure

We don't use all common extern files present in closure compiler. Extern files gathering browsers specific api are not included. 
That being said, some API that are now standard are still defined in those extern files. 
That just requires a big cleaning in the extern files that we will do at some point.

**Comment by jDramaix** [comment]
Fixed with https://github.com/google/closure-compiler/commit/e4118f33e107498cf958a3487fbd25cf730e5002
