### ISSUE TITLE
HTMLTextAreaElement missing placeholder attribute

### ISSUE THREAD

**Issue by anbuck** [google/elemental2#110]
The HTMLTextAreaElement class should have a **placeholder** attribute, just like the HTMLInputElement does.

**Comment by realityforge** [comment]
I think this issue can be closed. The upstream externs have been updated to include this attribute a while ago so the next official release will include this attribute.

In the meantime you can use a more recent unofficial release. Notes on how to use it are in the post

https://groups.google.com/forum/#!topic/google-web-toolkit/Hofnjq983Ew
