### ISSUE TITLE
location isn't a Location in IE11, Edge

### ISSUE THREAD

**Issue by niloc132** [google/elemental2#12]
This is going to be a stretch... but let's talk it out anyway.

It turns out that GWT (and J2CL)'s type checking that is done on `@JsType` objects breaks on the `window.location` instance in basically any browser made by Microsoft, since as the title says, `location` isn't a `Location`.

Bug report filed with Microsoft: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14307901/

![screen shot 2017-10-19 at 4 18 14 pm](https://user-images.githubusercontent.com/241630/31799539-459c9d1e-b500-11e7-983c-5e39b7496151.png)

The first two are sane enough, but the third is not quite right, and the fourth seems internally inconsistent, how can an object not be an instance of its own type's constructor.

The workaround is to either never need to cast to Location (which is a problem, given that Location is missing pieces, and updates haven't proven to be timely), or mark Location objects as actually just plain Object:

```
@JsType(name = "Object", namespace = JsPackage.GLOBAL, isNative = true)
public class Location {
```

If you happen to make your own Location object (because elemental2's is broken), you must do this, or use unchecked casts to convert. In the future when Elemental2 has a working Location object, but there is some annoying bug elsewhere in Elemental2, casting from an external library's location _to elemental's_ will have this problem.

If we cannot expect prompt updates, we need casts to be able to work to not compound hacks with more hacks - and even then, it might be wise to expect `instanceof` to behave as expected.

So, if you'll forgive the hyperbole, I think we might benefit from bending the rules here, if it isn't too difficult to implement. Excluding a vendor's entire browser provider's offerings from functioning correctly due to a hard to identify bug seems... hard to accept.

**Comment by gkdn** [comment]
For corner cases where user needs a cast, Js.unsafeCast should take care of the problem.

**Comment by jDramaix** [comment]
Seems Microsoft is fixing the bug.

**Comment by niloc132** [comment]
Without reopening, can I ask how we should handle cases of cross-frame communication, where this same sort of thing will apply?

For example, `window.open` returns a `Window`, but not _my_ window's `Window`. So, if I open windows, or use iframes, and stick their `contentWindow` in a `Map<identifier, Window>`, the cast on the way out will fail every time.

Might be better handled as its own issue, or as part of 16/17, let me know and I'll update/create accordingly.

**Comment by gkdn** [comment]
The problem you are describing (multi-frame) is not really an elemental problem but it is more general jsinterop problem. Elemental can try to work around it but you may hit it in other places.
