### ISSUE TITLE
Missed members in History API interface

### ISSUE THREAD

**Issue by axls** [google/elemental2#13]
`elemental2.dom.History` doesn't contains next standard mebers:

* property `length`;
* function `go`;
* function `back`;
* function `forward`;

I can create PR, but I have a question.
History API extern's declaration splitted in html5.js and ie_dom.js. Should I to fully redeclare History API in `dom_missing_api` (including constructor and other stuff from html5.js), or it is enough to only add missed memebers in `dom_missing_api`?

**Comment by jDramaix** [comment]
just add missing members

Thanks
