### ISSUE TITLE
elemental2.dom.WebSocket#close(int code, String reason) throws InvalidAccessError: A parameter or an operation is not supported by the underlying object

### ISSUE THREAD

**Issue by Nirostar** [google/elemental2#133]
The two methods 
`elemental2.dom.WebSocket#close(int code, String reason)` and
`elemental2.dom.WebSocket#close(int code)` both throw an InvalidAccessError in Firefox (don't know if other Browsers work)
`elemental2.dom.WebSocket#close()` is working as intended.

**Comment by realityforge** [comment]
The Elemental2 browser apis just wrap the underlying browser API so I think that if you translated you code into javascript you would see the same problem. There is not enough details to guess what you are doing wrong ut I would check out the browser docs at https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/close

If I was to hazard a guess I expect you code is not in the set of allowable codes (i.e. 3000–3999 if you have registered it with IANA or 4000–4999 for application specific codes)

HTH

**Comment by Nirostar** [comment]
Thanks a lot. Now I feel dumb like bread. 🙈 I read the section about the codes, but I didn't read it well enough :S I was now trying the 2nd library for sockets and didn't see the problem. (The project previously used your `gwt-websockets` library). Now I can sleep easily.

**Comment by realityforge** [comment]
I have done exactly the same thing ... multiple times. Hence how I could guess ;)

**Comment by Nirostar** [comment]
I guess since the CloseFunction can only consume an Event, there is no possibility to get the CloseEvent and the closing code from it?

**Comment by realityforge** [comment]
I am not sure what you mean. `onclose` is called with a `CloseEvent` and I believe that is still invoked, even if you initiate the close. If you use the more generic `addEventListener` then you may need to cast the event to the correct type.

Although it has been a while since I looked at the code so it may be that the Elemental2 externs don't specify the types tightly enough and you ay need to always do a cast
