### ISSUE TITLE
The type javaemul.internal.ArrayStamper is not visible

### ISSUE THREAD

**Issue by stockiNail** [google/elemental2#134]
I'm using elemental2.dom version 1.0.0 on GWT 2.8.2.
When I'm compiling my project, I got the the following exception:

```
   [ERROR] Errors in 'jar:file:[...]/WEB-INF/lib/elemental2-core-1.0.0.jar!/elemental2/core/JsArray.java'
      [ERROR] Line 18: The type javaemul.internal.ArrayStamper is not visible
      [ERROR] Line 318: ArrayStamper cannot be resolved
   Tracing compile failure path for type 'elemental2.core.JsArray'
      [ERROR] Errors in 'jar:file:[...]/WEB-INF/lib/elemental2-core-1.0.0.jar!/elemental2/core/JsArray.java'
         [ERROR] Line 318: ArrayStamper cannot be resolved
         [ERROR] Line 18: The type javaemul.internal.ArrayStamper is not visible
```

In classpath there are all dependencies of elemental2.dom:

- base-1.0.0.jar
- elemental2-core-1.0.0.jar
- elemental2-dom-1.0.0.jar
- elemental2-promise-1.0.0.jar

**Comment by realityforge** [comment]
Unfortunately GWT 2.8.2 is not compatible with the 1.0.0 release. You can use the a more recent version of GWT - See https://groups.google.com/d/topic/google-web-toolkit/qmwiMVofhR8/discussion or use an earlier version  of elemental2

HTH

**Comment by stockiNail** [comment]
Thank you very much for fast reply.
I'm wondering about "more recent version of GWT" because officially the last version is [2.8.2](http://www.gwtproject.org/versions.html).

May I suggest to add into README page that the integration with current version of GWT is dropped?
That's becasue reading that page, I was sure that it works with last version of GWT and unfortunately it isn't. 
Is there any chance that in next version of elementals, this error will fix without using that class not visible?

**Comment by realityforge** [comment]
There is no official release after GWT 2.8.2 which is why you need to use an unofficial version of GWT which either means one of the nightlies or the version I linked to above. In theory someone will release the next version of GWT someday but I guess as most of the people who can do the release of GWT officially already use a master version, there has not been an incentive to do so.

It is unlikely the next version of Elemental2 will be usable in GWT 2.8.2 as I think Google is mostly focused on J2CL and/or GWT master - both of which have the file.  I am just a user of the products not a maintainer but that is my guess ;)

**Comment by stockiNail** [comment]
> There is no official release after GWT 2.8.2 which is why you need to use an unofficial version of GWT which either means one of the nightlies or the version I linked to above. In theory someone will release the next version of GWT someday but I guess as most of the people who can do the release of GWT officially already use a master version, there has not been an incentive to do so.

That's what I don't like... :(
Usually I prefer using official versions, mainly when you are providing libraries to others (as my case).
I can not ask to the users to use unofficial versions, mainly if the applications is running on production. 

Honestly I have some doubts to leverage on product versions by `master` branch because you don't have a consistent point and the master can change one second later you tagged your version. 

Anyway I'm not using elemental 1.0.0.RC1 and it works.

@realityforge  THANK YOU VERY MUCH for your reply, really appreciated.

**Comment by jDramaix** [comment]
The 1.0.0 release is not compatible with GWT 2.8 (Thisis why I don't mention this version in the README yet)
The community is working on [GWT 2.9](https://github.com/gwtproject/gwt/milestone/19) but I don't know when it will be released.
