### ISSUE TITLE
Build failure: `Executing genrule //java/elemental2/dom:w3c_event_patched failed`

### ISSUE THREAD

**Issue by niloc132** [google/elemental2#137]
This commit seems to have broken the build: https://github.com/google/elemental2/commit/d15d5132a5668b8781d99ef22b5673b3b659e268 

It assumes that https://github.com/google/closure-compiler/pull/3542 has already merged into google/closure-compiler, but this does not appear to be the case. As such, building elemental2 currently fails, since this diff does not apply cleanly.

**Comment by gkdn** [comment]
Elemental2 automatically syncs in earlier than JsCompiler so this is expected at the head version when a change  is submitted.

**Comment by niloc132** [comment]
Is there a rough ETA on the cycle completing? Looks like the lag time (of broken elemental2 and all downstreams) is 16+ hours.

**Comment by jDramaix** [comment]
I think closure guys are syncing every day or two days.

**Comment by niloc132** [comment]
Just a heads up, this is still broken even though closure has merged that patch.

This is because w3c_event comes from 
```
extern(
    name = "w3c_event",
    path = "browser/w3c_event.js",
)
```
and `extern(...)` uses the `com_google_javascript_closure_compiler` repository, which is _not_ from git (that would be `com_google_closure_compiler`, defined [here](https://github.com/google/elemental2/blob/master/build_defs/repository.bzl#L16-L20) to read from github directly), but from [rules_closure](https://github.com/bazelbuild/rules_closure/blob/master/closure/repositories.bzl#L659-L693) which specifies an old release.

This mismatch was discussed in https://github.com/google/elemental2/pull/135 - my understanding was that the conclusion from that was that we should stop using the "master" build, but only use the latest release. Likewise as discussed there, the `extern()` def does not read from the "master" branch, so I think it was premature to merge this. Would you consider reverting it so we can build this project (and downstream projects) again?

Alternatively, replace the `extern(...)` invocation above with an `alias(...)`, like in #135?

**Comment by jDramaix** [comment]
My last comment were wrong for most of the extern files, I'm sorry. 
We use extern files packaged in jscompiler binary (to be sure the api are sync between the externs used by the jscompiler and the interfaces defined in elemental2). So we need to wait that a new binary containing the changes in the externs is released. Then we update rules_closure repo to use this new release and that will fix the build.

We need to switch on a monthly release so people does not need to depend on master.

**Comment by niloc132** [comment]
There is a PR open that will resolve this until the next release is shipped: https://github.com/google/elemental2/pull/138

As elemental2's build instructions direct users to use `master` (as does the tagged release, even though the tagged build appears to use a tagged version of closure-compiler, which may resolve this), it might make sense to fix this issue - any project following the readme instructions cannot build and hasn't been able to do so for just over a week.

**Comment by gkdn** [comment]
To clarify;
Internally we use everything from HEAD version so any update goes directly here; I don't know anyway to delay that.
Externally we need to use the externs from the JsCompiler version used by rules_closure.

So there is no way to make head version work always until we stop looking at two different places.

@jDramaix is that something we could speed that up?

**Comment by jDramaix** [comment]
We could think about doing a monthly release (in sync with closure compiler release) so people can use this one instead of depending on master and update the build instructions.
Master will always be instable externally.
Or we could push changes to a branch instead of master and merge to master once this temporary branch is stable.

**Comment by gkdn** [comment]
Do you expect instability after everything is moved under jscompiler and patches are gone?

**Comment by jDramaix** [comment]
The only way to remove patches is to write specific visitors. There is no way to fix everything in the extern file directly. EventListener is an example of api that would need post process to fix the generated java code.
Even if we get rid of the patches, we can have instability if they rename/move extern files (they did that recently and will do it again) and with integer entity files.

**Comment by jDramaix** [comment]
Note that we don't have instability with integer entity files as the jsinterop generator runs in non-strict mode in opensource and it emits a warning instead of an error.

So I guess if we can rid of the patches, master branch of elemental should stay stable. Closure guys will rename so extern files in the near future but then it should not happen anymore
