### ISSUE TITLE
CanvasPattern does not have the setTransform method

### ISSUE THREAD

**Issue by garthhenning** [google/elemental2#145]
The CanvasPattern created by a canvas' context should have one method to setTransform() per the spec. The method should take either a DOMMatrix or an SVGMatrix. 

https://html.spec.whatwg.org/multipage/canvas.html#dom-canvaspattern-settransform
https://developer.mozilla.org/en-US/docs/Web/API/CanvasPattern/setTransform

**Comment by jDramaix** [comment]
cOuld you propose a change in the extern file on google/closure-compiler project? Just add the missing method(s)

**Comment by zbynek** [comment]
Downstrem PR https://github.com/google/closure-compiler/pull/4154/files

**Comment by jDramaix** [comment]
Thanks for the contribution
