### ISSUE TITLE
Deriving a browser API from WebIDL

### ISSUE THREAD

**Issue by realityforge** [google/elemental2#147]
A while ago I started to experiment with generating a typed browser API by processing WebIDL definitions from the specifications. Microsoft does something similar for typescript and I figured it would be nice to do the same for GWT/J2CL. The ultimate goal was to get it good enough that I could pitch the idea back to you to see if you would be interested in me contributing it here.

The library is not yet ready for widespread use and still undergoing experimentation but so far I like where it is going. Along the way I started to scrape MDN for documentation to feed into javadocs and will soon ingest the browser compatibility data that drives the MDN site so it becomes easier to run a tool that verifies that an applications supports the browsers you want to support.

Anyhoo, I thought I would give you a heads up to see if it is something that you may be interested in long term. I mentioned it on the gwt gitter channel and a few people seemed interested. 

I am hoping to get it into a good enough state that we can cut out suite of applications across to it by the end of the year.

I don't emit closure externs at this stage. I did in the past but was not running any tests to verify they were correct so I stripped the extern generation and will add it back a little later. However I do generate jsinterop annotated classes. An example of what a jsinterop annotated class would like is

https://github.com/react4j/react4j-vchat/blob/master/src/main/java/elemental3/HTMLElement.java

(Sorry for generating to the elemental3 package name - I wasn't intending to step on any toes. This was mostly a spike to pitch internally and was using a name that people were already familiar with.)

The project is at https://github.com/realityforge/webtack and the content of the project README is below the line.

Anyhoo - I was just posting an issue to describe what I am doing and where I am hoping to go. Hopefully I can make it useful enough to pitch it to you guys down the track but feel free to have a poke around and/or comment on it ;)

---

## What is WebTack?

WebTack is a tool designed to fetch WebIDL and supporting artifacts, process the WebIDL and generate source code to support writing web applications.

[WebIDL](https://heycam.github.io/webidl/) is used by various specifications to communicate the interfaces that are expected to be implemented in web browsers. Many web browsers also use a WebIDL variant to generate code to implement the specification.

The types of source code artifacts that WebTack generates or will generate include:

* [Closure-compiler](https://github.com/google/closure-compiler) externs so that the closure-compiler
  can perform type checking and advanced type-based optimizations.
* Jsinterop annotated java classes that can be used in [GWT](https://github.com/gwtproject/gwt) or
  [J2CL](https://github.com/google/j2cl) based projects.
* [React4j](https://github.com/react4j/react4j) element factories.

WebIDL published as part of the official specifications are not always perfect representations of the interfaces as implemented by the web browsers. Nor is there a central place that contains the complete WebIDL that a browser is expected to implement. WebTack defines a pipeline for processing WebIDL schemas. The pipeline defines a series of stages. Each stage will either transform a schema, combine multiple schemas or perform an action for the schema. This capability allows WebIDL or process the WebIDL schemas fetched from the specifications and combine them into a consistent document.

WebTack also includes tools to fetch data from other locations and combine the data with the WebIDL in processing stages. The most significant other data source is the documentation that is scraped from the [MDN](https://developer.mozilla.org/en-US/) website and used to add basic documentation to the WebIDL elements. In the near future it is expected that the [browser compatibility data](https://github.com/mdn/browser-compat-data/tree/master/api) will be also be scraped so that browser compatibility data for WebIDL elements can be used in the  processing pipeline to influence how artifacts are built. Other data from the web specifications could be combined to  improve the outputs. At the very least, links to the specifications will be added to the WebIDL elements in the future.

WebTack extends the WebIDL syntax to support additional data being added to the WebIDL. This includes syntax to explicitly declare events emitted by interfaces (i.e. there is a new member element that looks like `event ProgressEvent load;`). It also supports a [Javadoc-like](https://en.wikipedia.org/wiki/Javadoc) syntax for documenting the WebIDL elements.

The WebTack jsinterop action generates source code with a more java-esque feel than is present in [elemental2](https://github.com/google/elemental2). It also aims to offer affordances that make working with the browser API easier for java developers. A few differences from Elemental2 include:

* Javadocs are added for most fields, methods and types if the element is documented on MDN.
* Constants in WebIDL are represented as constants in java. This typically results in smaller code size and may open
  up additional optimization opportunities.
* Fields, methods and parameters are annotated with `@Nonnull` or `@Nullable` if the type is a non-primitive, non-void type.
* Read-only attributes in WebIDL are implemented as methods rather than mutable fields of properties with setters.
* Dictionaries in WebIDL use a "builder" pattern to make construction of these types much easier.
* No parameterized types exist in WebTack as WebIDL does not define such constructs.
* Event handlers and event listeners are typed according to type of event expected to be delivered and have a void
  return type. This simplifies the use of lambdas and method references in java code.
* `@JsOverlay` methods are added for known events emitted by an interface. For example, it is possible to use code such
  as `e.addBlurListener(this::processBlurEvent)` rather than the more verbose `e.addEventListener("blur", e -> processBlurEvent((FocusEvent) e)`
* WebIDL enumerations are annotated with the `@MagicConstant` annotation when translated to java code. The
  Jetbrains/IntelliJ IDE suite will detect this annotation and allow auto-completion of enumeration values or
  report errors when incorrect values are supplied.
* Several other minor usability improvements, particularly with respect to union types.

### The Now

Experiments with WebTack are ongoing but so far the experiments have largely proved successful. Several web apps have been created to explore the feel of using the generated code. This has included experiments with the [Web Bluetooth API](https://webbluetoothcg.github.io/web-bluetooth/) by creating a browser based [Heart Rate Monitor](https://github.com/react4j/react4j-heart-rate-monitor), experiments with [speech synthesis](https://github.com/react4j/react4j-webspeechdemo) using the [Web Speech API](https://wicg.github.io/speech-api/), experiments with [WebRTC](https://w3c.github.io/webrtc-pc/) by creating a [video chat application](https://github.com/react4j/react4j-vchat) and several other experiments that are not open source.

The experiments to date, have copied the WebTack generated source into the source tree. To facilitate experiments by third parties, the generated source code for the has been packaged and published to maven central. This artifact can be added as a maven dependency:

```xml
<dependency>
  <groupId>org.realityforge.webtack</groupId>
  <artifactId>webtack-elemental3-complete</artifactId>
  <version>0.02</version>
</dependency>
```

### The Future

WebTack is an alpha project that is surprisingly useful as is. It is extremely useful to start using web APIs that are not covered by [elemental2](https://github.com/google/elemental2) with minimal fuss. The web APIs are also generated with basic javadocs that makes it relatively easy to explore the API locally or follow a link to MDN for more details. The java API is usually equivalent or better than the equivalent in Elemental2 as it tries to follow conventions more comfortable to Java developers.

The outputs are not without limitations. The following limitations that have been discovered while using the outputs of WebTack.

#### Large Java Packages

WebTacks jsinterop action generates a java type for every element within the input WebIDL schema. These elements are mostly generated within a single java package. If a reasonably complete WebIDL is fed into the action this can produce a single package with 1200+ java classes. This is not the simplest structure to navigate and is not expected to be an efficient compilation module.

An approach that we have used to address this limitation is manually partitioning the schema into required subset needed by the application. This has been surprisingly effective at producing small java packages, at the expense of some manual labour. However, it is expected that this would not scale to larger applications. A better approach maybe to automatically partition the files into different packages based on the originating specification or some other grouping heuristic.

#### Browser Implementation Differences

Some APIs that applications are browser-specific and thus not included in the specification. Some browsers do not implement the specification exactly. The fix is to apply processor stages to adjust the schema to match the way browsers implement the specification. This is somewhat error prone as it involves detecting the error and applying the appropriate patch. A better solution is to import the browser specific WebIDL source files, detect differences and merge the differences as desired. This should be relatively easy for chrome and gecko based browsers that already have publicly available WebIDL files.

#### Missing/Incomplete Features

WebTack is missing a handful of features.

* Ths closure externs generator action has been removed as it was not being exercised as our test applications are
  not using J2CL.
* The `IterableMember` element in WebIDL does not yet result in any java code as no application has required that
  feature yet.
* Some of the type mappings from WebIDL to java are not mapped in a java-friendly manner. The most obvious example
  is how sequences of non-double numeric values or nullable non-double primitives are mapped to java. The numeric
  values are mapped to `java.lang.Double` as that will map to javascript `number` when compiled. It is unclear on
  the best strategy to address this mismatch.
* WebTack references several classes from `elemental2-promise` and `elemental2-core` libraries. These dependencies
  can and should be removed but this would require additional work that has not been done.

**Comment by gkdn** [comment]
Thanks for sharing @realityforge. This is an interesting project.

We also actually started with IDL and due to many IDLs having inconsistent extension it turned out to be quite painful. After that we started looking into d.ts and later finally settled down on Closure externs. @jDramaix could better summarize all the different pro/cons discovered during this process but IIRC essentially matching Closure externs was the lowest maintenance option and ultimately most important target for us since those are what J2CL code was checked against. There are lots of thought put into externs and TypeScript typings so  that is quite valuable to inherit as well.

Comments and ability to use data from MDN is very helpful. We actually always wanted such a feature. It is great to incorporate them into generated APIs.

Following are also actually quite interesting as well. I would like to discuss more about them:

  >jsinterop action generates source code with a more java-esque feel than is present"

I think we can incorporate some of those ideas. Let me know if there are other stuff not covered in your post.

  > Constants in WebIDL are represented as constants in java. This typically results in smaller code size and may open
up additional optimization opportunities.

This one is; I'm not sure. Why do they typically result in smaller code size? You will be embedding them to your final output instead of reading them from browser.

  > Read-only attributes in WebIDL are implemented as methods rather than mutable fields of properties with setters.

setters vs. getters is one of things we get back and forth but I'm not sure generating them inconsistently based on const is good. I would like to hear your take on it.

  > Dictionaries in WebIDL use a "builder" pattern to make construction of these types much easier.

What kind if builders do you use? Any problems did you hit?

@jDramaix what did we end up settling for with dictionaries, just plain objects?

  > Event handlers and event listeners are typed according to type of event expected to be delivered and have a void
return type.

Could you explain more how did you diverge from externs here?

  > @JsOverlay methods are added for known events emitted by an interface.

How do you extract known events?

  > WebIDL enumerations are annotated with the @MagicConstant

I think this is not good since you miss the type safety here. I wonder why you preferred this over enums?

  > Several other minor usability improvements, particularly with respect to union types.

Would like to hear more :)

**Comment by realityforge** [comment]
FWIW This library uses the same technique that is used to generate the Typescipt typings. It also started with the set of IDL sources as the typescript tool but it has evolved since then.

I would be interested in why WebIDL was problematic. Once I had a parser in place, extracting the WebIDL from the specifications was relatively easy and IIRC retrieving and parsing the entire gecko WebIDL was fine to. Partially as it is collected in one [place](https://github.com/mozilla/gecko-dev/tree/master/dom/webidl).  I looked at chrome and that seemed relatively easy to parse although I did not try and the WebIDL is scattered all over their repository. So I would need to figure out which ones to collect and parse. I don't see anything too arduous involved in parsing the chrome IDLs but it is a bit of grunt work. My ultimate goal is to read both of those WebIDL sources and blend it with the spec sourced WebIDL to get maximum coverage.

The specs do require some massaging at times. Sometimes because spec versions evolved and sometimes because WebIDL can not represent some differences. However I have a pipeline of transforms that make this relatively easy.

I can understand why you would want to stick with existing closure externs as it seems you guys have a lot of code going back years that makes changing those externs difficult. There is a lot of knowledge in the externs but a lot of it is dated. I submitted a few PRs to remove code that no browser had supported in ~8 years IIRC :) There is also some constructs that are just not representable in closure type system present in some specs (i.e. See WebAssembly externs).

The prospect of an automated, browser compliant set of closure externs that had low maintenance costs was what drove me to this project. Ensuring compatibility and a nice API for the WebGPU, WebXR and the GL*  specs seemed like something painful to track ... I am sure this is true i other specs as well but 🤷‍♂️ 

> > Constants in WebIDL are represented as constants in java. This typically results in smaller code size and may open
up additional optimization opportunities.
> 
> This one is; I'm not sure. Why do they typically result in smaller code size? You will be embedding them to your final output instead of reading them from browser.

It all depends on the specific constants but in most cases the symbol that represents the constant is larger than the underlying constant. And this is the primary way by which code ends up smaller. Then in some specific circumstances other optimizations happen.

Unfortunately jsinterop-generator+constants result in `<clinit>` being present in sometimes. A limitation wither either gwt or jsinterop-generator depending on who you ask but an issue regardless ;)

For some constant integer values either GWT or javac performs a few more optimizations. i.e. `if( WebSocket.CONNECTING == webSocket.readyState )` translates to the spiritual equivalent of `if( !webSocket.readyState )`. For other integer constants that participate in bit operations (just WebGL API?) these can be baked ahead of time. This is largely code golf but no reason not to do so when it can be automated ;)

For strings, GWT pulls the strings out into a string table and aliases the constant with a var which is usually smaller than the symbol and the string can be reused multiple times. We use brotli to compress the assets and that did not eliminate this advantage compared to using an extern. I haven't tried gzip but brotli is better in almost every test we run so I assume the same is true for it.

> > jsinterop action generates source code with a more java-esque feel than is present"
> 
> I think we can incorporate some of those ideas. Let me know if there are other stuff not covered in your post.

There is a few - I will try to collect and write up somewhere when I get a chance

> > Read-only attributes in WebIDL are implemented as methods rather than mutable fields of properties with setters.
> 
> setters vs. getters is one of things we get back and forth but I'm not sure generating them inconsistently based on const is good. I would like to hear your take on it.

Other developers seemed to like this ... although several also requested I add getters and setters for WebIDL attributes that are currently represented as fields to make it more "java-like" but I have so far resisted such things as I like copy-pasting javascript code and translating ;)

> > Dictionaries in WebIDL use a "builder" pattern to make construction of these types much easier.
> 
> What kind if builders do you use? Any problems did you hit?

The pattern is best understood by looking at [RTCReceiverAudioTrackAttachmentStats](https://github.com/react4j/react4j-vchat/blob/master/src/main/java/elemental3/RTCReceiverAudioTrackAttachmentStats.java). The only problem is that GWT does not seem to optimize method chains that return this. Closure seems to have no problem. Although I have not dug into the cause and if it can be improved by changing the code.

> > Event handlers and event listeners are typed according to type of event expected to be delivered and have a void
return type.
> 
> Could you explain more how did you diverge from externs here?

The spec defines the WebIDL for event handler as 

```
[LegacyTreatNonObjectAsNull]
callback EventHandlerNonNull = any ( Event event );

typedef EventHandlerNonNull? EventHandler;
```

and closure extern defines event handlers on each event handler property. Historically they have been defined sufficiently for use in javascript (i.e. `@type {?function(Event)}` or `@type {?function(!Event)}`). For ones I was using, I started to submit changes so the externs started to return void ala

```
/**
 * An event handler called on open event.
 * @type {?function(!Event): void}
 */
WebSocket.prototype.onopen;
```

and in some cases adding the "correct" event typing ala

```
/**
 * An event handler called on close event.
 * @type {?function(!CloseEvent): void}
 */
WebSocket.prototype.onclose;
```

These patches took a long time to get through at times and some were rejected because it had too great an impact on internal codebases ... or so I believe. Given sufficient time and effort the changes could be applied across the closure externs. I actually considered writing a WebIDL parser back then to help me do this ;)

Event listeners are a bit more a synthetic artifact. For example the `WebSocket.prototype.onclose` event handler is actually mirrored  by an underlying `close` event. The is detected by scraping MDN through a chain of actions.

1. We scan and fetch the WebIDL from the [whatwg HTML spec](https://html.spec.whatwg.org/), which defines `WebSocket` type and download it to [whatwg_html](https://github.com/realityforge/webtack/blob/master/data/idl/whatwg_html.webidl)
2. Then we scan the MDN website based on a bunch of heuristics we end up at https://developer.mozilla.org/en-US/docs/Web/API/WebSocket where scrape links to other properties, functions and event pages and download the resulting page set to  https://github.com/realityforge/webtack/tree/master/data/docs/WebSocket
3. This eventually results in `close` event data downloaded to https://github.com/realityforge/webtack/blob/master/data/docs/WebSocket/close_event.json
4. A processing pipeline will pick this data up and will decorate the idl (using a custom event definition syntax) as well as change the type of the event hander property to match the data.
5. The jsinterop action then reads this idl and will generate the [CloseEventListener](https://github.com/react4j/react4j-vchat/blob/master/src/main/java/elemental3/CloseEventListener.java) as well as https://github.com/react4j/react4j-vchat/blob/master/src/main/java/elemental3/WebSocket.java#L296-L328

You could probably use the data I have already scraped along with a small mapping table (as not all closure extern types are named as the underlying browser types) and add the same transform to event handlers, event listeners and add javadocs as well in Elemental2. If you wait a month or two I will hopefully have got off my butt and scraped method parameters and return types too! You may also be able to completely eliminate the integer type listing in elemental2 by reading from the webidl data already fetched and looking at the types in the webidl. It also means you can use more precise types (i.e. double, float, int, short rather than just integer or double)


> > WebIDL enumerations are annotated with the @MagicConstant
> 
> I think this is not good since you miss the type safety here. I wonder why you preferred this over enums?

I originally went down this path but we are still on GWT :( I wanted a zero cost abstraction whereas enums in GWT result in all values unable to be DCEd. I presume `@JsEnum` in J2CL eliminates this issue but I haven't experimented and it is likely that when we get to J2Cl we will re-asses this part. 

`@MagicConstant` gives an okay safety in intellij in that you get big red wiggly lines and compile errors if you use the wrong one but it also allows you to use browser specific values that I thought may be required ... although in our experiments we have yet to require any non-standard enum values.

**Comment by realityforge** [comment]
I just had a poke around and it looks like replacing the current enumeration strategy with a "real" java enumeration annotated with `@JsEnum` is reasonably trivial (and results in much simpler code in webtack). This could probably be supported in tandem without too much effort.

**Comment by realityforge** [comment]
It should also be noted that there is a handful of scenarios that closure externs can represent typing not available in WebIDL that you end up having to special case. The most obvious case being `MessagePort.postMessage()` where the transfer list should be types that have the extended property `[Transferable]` attached but custom code is required when translating to java or closure externs.

**Comment by jDramaix** [comment]
So let me jump into this conversation.
First thanks for sharing our work with us @realityforge 

> We also actually started with IDL and due to many IDLs having inconsistent extension it turned out to be quite painful. After that we started looking into d.ts and later finally settled down on Closure externs. @jDramaix could better summarize all the different pro/cons discovered during this process

When I started the project 5 years ago, I used the WebIdl road. I had the prototype working using WebIdl from firefox and Chrome but we were not really happy with the generated api and decided to go with externs files. I don't remember exactly all the problems we reached with WebIdl but the main ones were:
- api desynchronization with extern files provided by closure compiler. This is a big issue for j2cl apps and requires that you generate your own extern files and uses them instead of using the standard ones. This is not working for apps that uses a mix of j2cl and closure code. 
- Typing is less expressive in WebIdl. You don't have type parameters (generics) for example (except for a few core type like promise, sequence...) 
- no WebIdl for javascript core api. elemental2-core and elemental2-promise cannot be generated from WebIdl as there is no WebIdl for that. 

> @jDramaix what did we end up settling for with dictionaries, just plain objects?
Dictionaries are java interface in Elemental2. We have a static factory method on each dictionary interfaces in order to instantiate an empty instance and then you can use setters. We can add builder pattern if needed: we had a discussion about that in https://github.com/google/elemental2/issues/6

In general, I think the improvements you mentioned can be added to Elemental2 instead of creating a new library. We can use WebIdl and any other sources of information for creating metadata files used by jsinterop generator for generating better code. I created the initial version of Integer-entities files by parsing WebIdl files for example.

**Comment by realityforge** [comment]
> * api desynchronization with extern files provided by closure compiler. This is a big issue for j2cl apps and requires that you generate your own extern files and uses them instead of using the standard ones. This is not working for apps that uses a mix of j2cl and closure code.

Still problematic if you live in that world. 

> * Typing is less expressive in WebIdl. You don't have type parameters (generics) for example (except for a few core type like promise, sequence...)

Typing is **different** between WebIDL and closure externs. There are several constructs that the closure typing system is unable to represent adequately that are present in WebIDL and thus web APIs. WebIDL is primarily about representing a browser API and thus I haven't seen many problems generating a browser API layer from it. There is occasionally a construct I would like to see generated that is not representable in either WebIDL or closure-externs but is representable in more expressive system like Typescript (`HTMLCanvaseElement.getContext(...)` being an obvious example) but nothing that I have wanted that closure-externs can represent that is not available in WebIDL.

FWIW a different perspective: When the closure externs introduced some of the parameterised types into core (and thus elemental2 classes stopped being able to compile with linting enabled) was when we got off the Elemental2 train. We didn't find that it offered many benefits to java developers but YMMV.

> * no WebIdl for javascript core api. elemental2-core and elemental2-promise cannot be generated from WebIdl as there is no WebIdl for that.

Still an issue. However the code currently part of elemental2-(core|promise) is not always the easiest to work with as is. I have experimented with defining some types in WebIDL and generating from that but even that has not produced great code. For this I am looking at a combination of WebIDL and manually written code. The hope is that with some hand hackery, working with types like `JsArray` will not be too onerous.

> In general, I think the improvements you mentioned can be added to Elemental2 instead of creating a new library. We can use WebIdl and any other sources of information for creating metadata files used by jsinterop generator for generating better code. I created the initial version of Integer-entities files by parsing WebIdl files for example.

Given enough effort it could be possible.

Once we have got all the data assembled I will send another ping ;)

**Comment by gkdn** [comment]
Keep in mind that typings are opinionated. There are coercions done with the API so many APIs would get any type (and I expect WebIDL to reflect that) however extern will limit that.

For the record, I am expecting externs to be eventually replaced by TypeScript typings but I will not hold my breath for it.
