### ISSUE TITLE
WebGL constant type mismatch

### ISSUE THREAD

**Issue by zbynek** [google/elemental2#149]
```
public native Object getShaderParameter(WebGLShader shader, int pname);
```
expects `WebGLRenderingContext.COMPILE_STATUS` but `COMPILE_STATUS` is a double.

Maybe the constants are just missing from [integer entities](https://github.com/google/elemental2/blob/master/java/elemental2/webgl/integer_entities.txt)? Proposed patch in #150

**Comment by gkdn** [comment]
@jDramaix

**Comment by zbynek** [comment]
Fixed in https://github.com/sgammon/elemental2/commit/27d8c945b078b9273f188eaec5123f442271813e
