### ISSUE TITLE
window.onerror is missing column, error arguments

### ISSUE THREAD

**Issue by niloc132** [google/elemental2#15]
As of HEAD:
```
  @JsFunction
  public interface OnerrorCallbackFn {
    Object onInvoke(String p0, String p1, double p2);
  }
```
From [whatwg spec](https://html.spec.whatwg.org/multipage/webappapis.html#onerroreventhandler)

    [TreatNonObjectAsNull]
    callback OnErrorEventHandlerNonNull = any ((Event or DOMString) event, optional DOMString source, optional unsigned long lineno, optional unsigned long colno, optional any error);

From [MDN](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror):

> window.onerror
> 
>     window.onerror = function(messageOrEvent, source, lineno, colno, error) { ... }
> 
> Function parameters:
> 
>   * message: error message (string or event object). Available as event (sic!) in HTML onerror="" handler and also as an event object when dispatching an Event to window in which case the other arguments will not be supplied (as opposed to ErrorEvent which does cause the full range of arguments to be supplied to window.onerror whereas the single error event object is supplied to window.addEventListener('error') handlers) .
>   * source: URL of the script where the error was raised (string)
>   * lineno: Line number where error was raised (number)
>   * colno: Column number for the line where the error occurred (number)
>   * error: Error Object (object)
> 

Of note, this document also indicates that the last two arguments were missing from firefox until version 31 (though, this is almost old enough to still support the legacy dev mode plugin...).

Notes at https://github.com/google/closure-compiler/blob/master/externs/browser/w3c_dom1.js#L873 appear incorrect - msdn link redirects to a different MDN on the error event with no other detail about this, and the MDN link is the one I quoted above.

I wasn't sure if you wanted this filed upstream, or instead made into a diff as with most of the other bugs in closure externs, so I filed it here for triage.

**Comment by jDramaix** [comment]
Thanks I'm fixing that upstream internally.

**Comment by jDramaix** [comment]
fixed with https://github.com/google/closure-compiler/commit/7bee1ca1beaa4f9695a02d0130e915f0e65ac3c6
