### ISSUE TITLE
HTMLElement click() missing

### ISSUE THREAD

**Issue by anbuck** [google/elemental2#152]
In previous versions of the library there was a click() method to for HTMLElement to match this method from javascript: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click

But in the latest version of the library it has been removed. How should we programmatically trigger a click on an element now?

**Comment by haquee** [comment]
I am facing the same issue. The click() method disappears in version 1.0.0 but no mention about the deprecation.
