### ISSUE TITLE
Add Clipboard APIs

### ISSUE THREAD

**Issue by zbynek** [google/elemental2#154]
As developer I'd like to access navigator.clipboard, ClipboardItem class and related APIs via Elemental. The support in Closure looks  pretty god: https://github.com/google/closure-compiler/blob/master/externs/browser/w3c_clipboard.js, hopefully it's enough to add this extern to Elemental2. Ideally this should be added to elemental2-dom, alternatively to a new module.

**Comment by hpehl** [comment]
@jDramaix, any updates on this?

**Comment by gkdn** [comment]
Fixed in https://github.com/google/elemental2/commit/19a97aa23958b65943b98506bd4f26f31ea98d93
