### ISSUE TITLE
Missing properties of HTMLTextAreaElement and TextMetrics

### ISSUE THREAD

**Issue by jiakuan** [google/elemental2#160]
Some important properties such as `selectionStart` and `selectionEnd` are missing in `elemental2.dom.HTMLTextAreaElement`.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement

**Comment by zbynek** [comment]
These are defined in `gecko_dom` extern so it would be solved by https://github.com/google/elemental2/issues/86 or by moving standard definitions from `gecko_dom` to the default extern as suggested in https://github.com/google/closure-compiler/issues/2478

**Comment by gkdn** [comment]
@jDramaix Given reluctance in closure compiler to move them; maybe we should just include gecko_dom. Are they any negatives to that?

**Comment by zbynek** [comment]
One downside of including gecko_dom as is that it would expose many non-standard or nonexistent APIs, e.g. `Element.prototype.firebugIgnore`, `Window.prototype.controller`, ...

**Comment by jiakuan** [comment]
Similarly, most properties are missing in `TextMetrics` except `width` being there.

As a temporary workaround, I created a new type to use:

```
import elemental2.dom.TextMetrics;
import jsinterop.annotations.JsPackage;
import jsinterop.annotations.JsType;

@JsType(isNative = true, name = "TextMetrics", namespace = JsPackage.GLOBAL)
public class TextMetrics2 extends TextMetrics {

  public double actualBoundingBoxAscent;
  public double actualBoundingBoxDescent;
  public double actualBoundingBoxLeft;
  public double actualBoundingBoxRight;
  public double fontBoundingBoxAscent;
  public double fontBoundingBoxDescent;
}
```

**Comment by zbynek** [comment]
https://github.com/google/closure-compiler/blob/master/externs/browser/html5.js#L989 already has most of these so they should be included in next elemental release. The remaining ones (fontBoundingBoxAscent/fontBoundingBoxDescent) are not yet supported in FireFox.

**Comment by jDramaix** [comment]
I double checked and all missing api are now part of Elemental2. A new release is needed though.
