### ISSUE TITLE
Add es6_proxy.js,w3c_pointerlock.js and w3c_gamepad.js

### ISSUE THREAD

**Issue by treblereel** [google/elemental2#163]
I think it would be great to have these APIs in elemental2; they are standardized and should not cause any issues.

es6_proxy.js probably should be added to the core
w3c_pointerlock.js to dom
w3c_gamepad.js to media

If the Google team agrees, I can prepare a PR.

**Comment by gkdn** [comment]
@jDramaix any concerns?

**Comment by jDramaix** [comment]
I don't have any objections.

**Comment by treblereel** [comment]
https://github.com/google/elemental2/pull/164

**Comment by treblereel** [comment]
merged, thanks
