### ISSUE TITLE
Window is missing postMessage

### ISSUE THREAD

**Issue by niloc132** [google/elemental2#17]
Dovetailing into #16... it turns out that elemental2's `Window` actually doesn't have a `postMessage`!

https://www.w3.org/TR/2009/WD-html5-20090423/browsers.html#windowproxy shows it, but for some reason closure (and therefore elemental2) fails to allow it on the window object, only on global. In `html5.js`:
```
/**
 * This is a superposition of the Window and Worker postMessage methods.
 * @param {*} message
 * @param {(string|!Array<!Transferable>)=} opt_targetOriginOrTransfer
 * @param {(string|!Array<!MessagePort>|!Array<!Transferable>)=}
 *     opt_targetOriginOrPortsOrTransfer
 * @return {void}
 */
function postMessage(message, opt_targetOriginOrTransfer,
    opt_targetOriginOrPortsOrTransfer) {}

```

It should almost certainly be attached to `Window.prototype` as well, or instead of a static method.

**Comment by jDramaix** [comment]
feel free to open a bug in the closure repository and discuss there.
