### ISSUE TITLE
Build should generate maven-compatible jars, poms

### ISSUE THREAD

**Issue by niloc132** [google/elemental2#19]
Presently, the bazel build for elemental2 generates a few jars, but they seem difficult to use at this time in gwt2 projects.

For any module $MODULE here, we get these jars:
 * lib$MODULE.jar - contains .class files and .gwt.xml
 * lib$MODULE-class.jar - contains only .class files
 * lib$MODULE__internal_src_generated.jar - contains only .java files

In contrast, currently in maven central we have a regular jar file, with .java, .class, and .gwt.xml, a -classes jar with only .java files (perhaps should contain .gwt.xml as well?) as well as a pom which declares dependencies.

This issue is to track the ability to generate jars suitable for use in gwt2, and a mechanism for deployment (be it maven or gradle) to binary repositories for downstream use. I'm aware that there is a mechanism which can be used inside of Google, but for open source contributions and forks this can enable non-googlers to deploy snapshots or releases with fixes more directly.

**Comment by realityforge** [comment]
I know it is annoying to get a "me too" comment an issue but me too. We would love to see the build infrastructure in place so at the very least it is trivial to self-publish.

We had planned to try an automatically publish to our own artifact repository on each commit to elemental2 project but were stymied by this and lacked the cycles to investigate a solution.

Even if there was some basic instructions on how to do this in the README it would be a big help.

BTW Thanks for your work on Elemental2 ;)

**Comment by niloc132** [comment]
I've done almost no concrete work, all the credit has to go to Julien and the GWT team - I just field a lot of questions from the community, and sometimes the only way I can help is to file the bugs!

However, I think this is a case where I might be able to finally contribute something... give me a few days, I've been learning a lot of bazel recently, but it all still feels like ant rewritten in python. Without Ivy. And decent (if confusion/contradictory) IDE completion.

**Comment by tbroyer** [comment]
Fwiw, maybe have a look at how Dagger does it (hint: python and bash and bazel)

**Comment by jDramaix** [comment]
I have a bash script that build the artifacts and upload them to sonatype. 
I will check if I can create a os_build.sh based on that script that works with bazel.

**Comment by niloc132** [comment]
Otherwise the bash script itself (or a simplified version) would be more than enough if you can share, we can figure it out from there (or from what dagger2 already has), which was going to be my starting point.

**Comment by jDramaix** [comment]
If have a script that is in review internally. Should be pushed next week.

**Comment by jDramaix** [comment]
Fixed with 28dddcda27fab069e71bf403771b0e675bc6b1dc
