### ISSUE TITLE
Latest release is incompatible with latest jsinterop-base release

### ISSUE THREAD

**Issue by niloc132** [google/elemental2#20]
Latest elemental2 release is 1.0.0-beta-1 (released April 5, 2017), and in `Document` has the inner type `CreateTextNodeDataUnionType`, which defines:

    @JsOverlay
    default double asDouble() {
      return Js.castToDouble(this);
    }

However, latest jsinterop-base release is 1.0.0-beta-2 (released May 5, 2017) has a `Js` class with no `castToDouble`. Instead, it has

    @SuppressWarnings("ReferenceEquality") // GWT is not good at optimizing equals
    public static double asDouble(Object obj) {
      checkType(Js.typeof(obj) == "number");
      return InternalJsUtil.asDouble(obj);
    }

This results in a compile-time error with GWT 2 (and a runtime error with j2cl).

**Comment by gkdn** [comment]
We are working on new jsinterop.base release and in the process of releasing source in a repo as well.

**Comment by jDramaix** [comment]
fixed with 70c4a8560bbaabc77ea5a383e89fa811f2e51210
