### ISSUE TITLE
Window.prompt has wrong return type

### ISSUE THREAD

**Issue by tbroyer** [google/elemental2#21]
`window.prototype.prompt` is added to `w3c_dom2.js` by [the patch in the repo](https://github.com/google/elemental2/blob/00b8a0e81f030e92cabd3a4883bbc403818b2b0c/java/elemental2/dom/w3c_dom2.js.diff#L133-L138) with no specified return type, so it's generated as `java.lang.Object`.

`window.prototype.prompt` is however already defined in Closure externs (in [`window.js`](https://github.com/google/closure-compiler/blame/7a8ec18b20b1738a92c41dae517b63a32c28d3d6/externs/browser/window.js#L166-L171), for more than 7 years!) with the correct return type.

There's another difference between those 2 definitions though (besides the return type): that the first argument is made optional in Elemental2 (which is more correct); so it would look like the fix would be to declare the return type as `@return {?string}` in Elemental2's `w3c_dom2.js.diff`.

**Comment by tbroyer** [comment]
Also note that `DomGlobal.prompt` is not redefined: first argument is not optional (i.e. there's no zero-arg `DomGlobal.prompt()`, and the return type is –correctly– `String`).

The same applies to `confirm()` with `boolean` vs. `Object` return type, and same discrepancy between `DomGlobal` and `Window`.

**Comment by jDramaix** [comment]
just a clarification:
- window.prototype.prompt present in w3c_dom2.js defines the method prompt() in Window.java class
- window.js defines the method prompt on the global scope and so define the method prompt on DomGlobal.java.

I'll sync both definitions

**Comment by jDramaix** [comment]
LGTM thanks for the patch

**Comment by jDramaix** [comment]
Sorry I've LGTM'd the issue and not the patch =)

**Comment by jDramaix** [comment]
Fixed with 380f242169927c7394bbac9ebc5b221f36f044e7
