### ISSUE TITLE
JsArray<String>.slice() always causes ClassCastException

### ISSUE THREAD

**Issue by niloc132** [google/elemental2#28]
Apologies if this should not be a bug (or should be filed against GWT itself), but it was a surprise to discover (and a pain to debug) - `JsArray<T>.slice()` returns `T[]`, which always causes a class cast exception, at least where T is `java.lang.String`. Workaround: use JsString or Object.

Steps to reproduce:

        JsArray<String> strings = new JsArray<>("a", "b", "c");
        String[] sliced = strings.slice();
        DomGlobal.window.alert(sliced[0]);

Replace `String` with either `JsString` or `Object` above, and it will work. Note that `Double` fails in the same way, despite ostensibly also being a value that can be passed interchangeably in and out of other JS methods. In fact, it appears that even elemental2 expects that this will work correctly: `elemental2.core.ITemplateArray` apparently extends `JsArray<String>`.

I'm not sure how this issue can be reasonably mitigated, aside from baking checks into GWT that this sort of thing isn't safe. Perhaps those methods should be annotated with `@UncheckedCast`?

**Comment by gkdn** [comment]
> despite ostensibly also being a value that can be passed interchangeably in and out of other JS methods. 

String[], Double[] etc. are not interoperable with javascript; they need marking to follow JLS. Right now if you them on a jsinterop method, you should get warning.

>  it appears that even elemental2 expects that this will work correctly: elemental2.core.ITemplateArray apparently extends JsArray<String>

JsArray<String> != String[] (if that is what you are referring to)

I don't think there is any easy way to mitigate this. If it is unchecked, it will result in broken types further leak into type system with more surprising effects.
My only solution to this was to mark these types automatically when they cross the jsinterop boundary.

**Comment by gkdn** [comment]
(And this effects both GWT and J2CL)

**Comment by gkdn** [comment]
@jDramaix how many API's use T[] on elemental? One solution is to covert those to Object[]; not ideal but less surprising...

**Comment by niloc132** [comment]
I know it would be far from ideal, but it wouldn't be possible to make this mistake with the kinds of restrictions that JSO originally imposed - JsArray<T> required T to extend JSO, etc. Clearly JsInterop is trying to avoid this sort of restriction, but it seems that at some level (not language, but compiler?) it might be constructive to have.

FWIW, same issue came up today from a gwt user in discussions on gitter - other values that "seem" to work as values like short, int, don't work in short[]/int[] arrays. As makes sense once you understand how it all works under the hood, I'm just concerned about requiring that level of knowledge and leaving errors to runtime surprises.

**Comment by tbroyer** [comment]
Wrt this specific issue, should those methods return JsArray instead?

**Comment by niloc132** [comment]
I suspect that the problem with `JsArray<T>` return type is that these methods are generated by elemental2, but the `JsArray` type is in elemental2 core itself, so elemental2 doesn't assume that core is already generated, etc.

**Comment by gkdn** [comment]
It can generate JsArray<T> but maybe Object[] would be more helpful? It will be good to see API changes to make a call. Will talk to Julien when he comes back.

**Comment by tbroyer** [comment]
At a minimum I think `JsArray<T>` methods should return `JsArray<T>` (methods on other classes could continue to return arrays); there might be other classes/methods with similar cases (maybe all "generic arrays" should be `JsArray`s?)

**Comment by JamesXNelson** [comment]
fwiw, when I've been using JsArray, I always disliked that it transformed back into a java array.  Once I know I have a JsArray, I'd much rather have access to js methods like `push()` or `slice()` than a java array.  Perhaps a single overlay method, `T[] asArray()` where it would be reasonable to emit warnings / break compiles if something unsupported (String[], Double[], etc) is attempted.

**Comment by gkdn** [comment]
@JamesXNelson  There is no asArray() any more. It is only asList() now.

@jDramaix See questions/discussion above.

**Comment by jDramaix** [comment]
I'll generate both solutions (JsArray<T>, Object[]) in order to evaluate the impact of each solution

**Comment by JamesXNelson** [comment]
Ah.  I was actually making up a method name called `asArray`, as a way to suggest "use JsArray everywhere, and if user wants a java array, give them one method to do it, so we can reduce the surface area of 'you thought having using an array of strings from javascript would be easy, didn't you?'".

Basically, if user wants String[], they probably shouldn't use JsArray, and if they use JsArray, they probably want to keep using JsArray.

**Comment by niloc132** [comment]
It appears that it isn't sufficient to be interoperable with javascript with `@JsType` - if you have a non-native type, it cannot be used through JsArray.slice() either. Yes, I do understand that these are treated differently, but it probably should be made clear in language/documentation that while JsType makes you code "interoperable", the various elemental2-core and jsinterop-base types for now need more than interoperable, they will only function with native js types?

Also, `JsArray.from(T[])` suffers from the same issues, though surprisingly this has the `uncheckedCast` on the parameter, but not on the output of `from(JsArray<T>)` where it is needed for this set of issues.

**Comment by ibaca** [comment]
Not been able to chain JsArray call is a downside of returning T[]. Are there any conclusion about returning JsArray<T> instead of T[]? (sorry, this is kind of a ping)

**Comment by gkdn** [comment]
We are currently leaning towards replacing all arrays with JsArray<T> which will be iterable via `#asList` and convertible to array via `toArray(Class<T> clazz)`. This needs to finalized before 1.0 release.

(@jDramaix: pls also collect feedback from here as well.)
