### ISSUE TITLE
Remove obsolete Text.replaceWholeText method

### ISSUE THREAD

**Issue by vegegoku** [google/elemental2#29]
Dears
According to a question i asked on gitter gwt channel about the `elemental2.dom.Text` where calling the method `replaceWholeText` will throw `replaceWholeText is not a function` exception, @niloc132 forwarded me to this documentation :
https://developer.mozilla.org/en-US/docs/Web/API/Text/replaceWholeText

and according to this this method is Obsolete and should not be included in the API.

Thanks

**Comment by vegegoku** [comment]
PR created https://github.com/google/closure-compiler/pull/2889

**Comment by jDramaix** [comment]
Thanks for the contribution
