### ISSUE TITLE
Missing `HTMLSpanElement`

### ISSUE THREAD

**Issue by CGJennings** [google/elemental2#32]
Version: 1.0.0RC

There is no `elemental2.dom.HTMLSpanElement` for representing `<span>` elements.

Although `HTMLSpanElement` adds no new properties or methods to `HTMLElement`, it [does have its own interface in the spec](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-span-element). (Whereas other, similar elements do not: there is no `HTMLStrongElement`.)

**Workaround:** One can use the `HTMLElement` class to represent `<span>`s, but this is bad type safety given their workhorse nature. (Presumably this is precisely why W3C gave it its own interface.)

**Comment by hrstoyanov** [comment]
any progress on that? When is the net elemental2 drop going to be done?

**Comment by jDramaix** [comment]
This will be fixed by fixing #86
