### ISSUE TITLE
Window.setTimeout and Window.clearTimeout methods are missing

### ISSUE THREAD

**Issue by dnouls** [google/elemental2#35]
Maybe I am not up-to-speed with the specs but I am missing the setTimeout and clearTimeout methods in elemental. Are they left out with a specific reason ? Should I use something else ?

**Comment by realityforge** [comment]
The method we use are `elemental2.dom.DomGlobal.setTimeout(...)` and `elemental2.dom.DomGlobal.clearTimeout(...)` and they are available in `1.0.0-RC1` version at least.

HTH

**Comment by dnouls** [comment]
Ah thanks, I was looking in the wrong place!
