### ISSUE TITLE
Missing Element.outerHTML

### ISSUE THREAD

**Issue by CGJennings** [google/elemental2#37]
Ver: 1.00RC

Closure definition is in `ie_dom.js`:
https://github.com/google/closure-compiler/blob/15e8c339cb9d6d88ca16181c529f809b233f077f/externs/browser/ie_dom.js#L1105-L1109

**Comment by realityforge** [comment]
A PR has been raised in upstream and we can close this issue once it has been merged. See google/closure-compiler#3397

**Comment by jDramaix** [comment]
Thanks

**Comment by realityforge** [comment]
This can now be closed as the PR has merged upstream
