### ISSUE TITLE
Element.id incorrectly declared in HTMLElement

### ISSUE THREAD

**Issue by CGJennings** [google/elemental2#38]
Version: 1.0.0-RC1

`HTMLElement` should inherit `id` from `Element`. In Closure externs, `Element.id` is found at [gecko_dom.js:756](https://github.com/google/closure-compiler/blob/15e8c339cb9d6d88ca16181c529f809b233f077f/externs/browser/gecko_dom.js#L749-L756), `HTMLElement.id` is found at [w3c_dom2.js:416](https://github.com/google/closure-compiler/blob/15e8c339cb9d6d88ca16181c529f809b233f077f/externs/browser/w3c_dom2.js#L411-L416).

Comments in gecko_dom suggest that `id` is defined on `HTMLElement` and `SVGElement` separately, but this is [no longer true](https://dom.spec.whatwg.org/index.html#interface-element).

**Comment by jDramaix** [comment]
**Contribution is welcome here.**

This need to be fixed in [google/closure-compiler repository](https://github.com/google/closure-compiler/) 
directly

**Comment by realityforge** [comment]
Submitted a fix in google/closure-compiler#3394 and once this is merged we can close this issue

**Comment by realityforge** [comment]
The PR landed upstream so this issue can be closed

**Comment by jDramaix** [comment]
Thanks!
