### ISSUE TITLE
HTMLElement.style.setAttribute throw style.setAttribute is not a function 

### ISSUE THREAD

**Issue by vegegoku** [google/elemental2#39]
GWT version : 2.8.2
elemental2 version : 1.0.0-RC1

using the `setAttribute` from elemental2 `CSSStyleDeclaration` gives `is not a function`, while using `setProperty` works.

to repeat the case add the following code snippet
```java
HTMLElement element= (HTMLElement) DomGlobal.document.createElement("div");
element.style.setProperty("padding-left","10px");//works
element.style.setAttribute("padding-right","10px");//fail

DomGlobal.document.body.appendChild(element);
```

the exception

```
App.java:13 Uncaught TypeError: element_0_g$.style.setAttribute is not a function
    at wzd_g$.xzd_g$ [as onModuleLoad_0_g$] (App.java:13)
    at Array.crb_g$ (org_00046sample_0004…MethodHolder.java:3)
    at initializeModules_0_g$ (ModuleUtils.java:44)
    at Dp_g$ (Impl.java:309)
    at Gp_g$ (Impl.java:368)
    at Impl.java:78
    at wqb_g$ (ModuleUtils.java:55)
    at App.java:9
```
i noticed that in the MDN documentation there is no `setAttribute` method
https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration

if it is something need to be fixed and i can make a PR for, i will gladly do.
Thanks

**Comment by gkdn** [comment]
Thanks for the report.
It seems like an old IE API. Probably it is old enough that nobody cares. Please send a patch to @google/closure-compiler to remove following line:
https://github.com/google/closure-compiler/blob/master/externs/browser/w3c_css.js#L528

**Comment by jDramaix** [comment]
It seems we cannot remove the method form the original extern file but we could potentially remove that api by patching the extern file.

**Comment by gkdn** [comment]
If we cannot remove, what about adding @deprecated?

**Comment by gkdn** [comment]
Ok that's actually what they did so I think we can close this.

**Comment by niloc132** [comment]
This will be much easier to notice by elemental2 users if https://github.com/google/jsinterop-generator/pull/6 is accepted, so that the `@Deprecated` is on the java types as well.
