### ISSUE TITLE
 Maven regards the current POMs as invalid

### ISSUE THREAD

**Issue by realityforge** [google/elemental2#41]
**Note:** This is the same issue as described in https://github.com/google/jsinterop-base/issues/2 except in elemental2. This problem is a greater impact for this project as elemental2 projects have correctly defined dependencies but Maven refuses to follow them. Anyhoo the following description is a copy of the jsinterop-base issue:

...

The POM generated by this project is invalid and generates warning such as the following when run through modern version of maven (3.5.3):

> [WARNING] The POM for com.google.elemental2:elemental2-dom:jar:1.0.0-RC1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

The problem is that the transitive dependency needs to be manually specified. Investigation seems to indicate that the problem is actually in the parent pom and simply updating to the latest parent pom fixes this.

The way to fix this is to change the pom output according to the following diff.

```
@@ -6,7 +6,7 @@
   <parent>
     <groupId>org.sonatype.oss</groupId>
     <artifactId>oss-parent</artifactId>
-    <version>7</version>
+    <version>8</version>
   </parent>
 
```

I am unfamiliar with the build system otherwise I would suggest the fix and assume that this should be a trivial fix for someone who is familiar.

If this is not the case then kick me and I can dive into it.

**Comment by realityforge** [comment]
It should be noted that the specific error that is emitted when debug is turned on is

```
Caused by: org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model for org.sonatype.oss:oss-parent:7
[ERROR] 'modelVersion' is missing. @ line 1, column 9
```

**Comment by realityforge** [comment]
It seems that this is not a problem with how elemental2 was published but a problem with proxies somehow caching incorrect dependency

**Comment by niloc132** [comment]
Worth perhaps also noting that this oss-parent is deprecated, and has been for some time. http://central.sonatype.org/pages/apache-maven.html#deprecated-oss-parent
