### ISSUE TITLE
Generating POMs in bazel

### ISSUE THREAD

**Issue by realityforge** [google/elemental2#46]
Is there any mechanism for generating poms in Bazel? A brief look around suggests that there is nothing in place atm.

Until there is would you consider a pull request that:

* checked in minimal poms for each jar in the location `java/elemental2/<module>/pom.xml`
* an enhancement to `build_gwt_mvn_jars.sh` that copied these poms to exist side-by-side with jars
* an enhancement to `build_gwt_mvn_jars.sh` that laid out the filesystem in a Maven2 compatible format.

This would make it a lot easier to integrate this into more traditional build systems.

**Comment by realityforge** [comment]
Anyhoo - I decided I need this so I went and implemented the above suggestion. Some ugly but functional code ;)

**Comment by niloc132** [comment]
Looks like the hard way is the only way at this time:
https://github.com/bazelbuild/bazel/issues/1372
https://github.com/bazelbuild/bazel/issues/30

Combined with the need to transitively update WORKSPACE to reference local projects when you are on a branch and required aggressive use of `clean --expunge` to avoid either pinned (i.e. already out of date) releases or stale local snapshots, I'm not sure anything other than manual is a good fit at this time.

**Comment by ronshapiro** [comment]
I just added something in https://github.com/google/bazel-common/commit/2782531da81d4002bce16e853953d9e8117a6fc1 - happy to discuss if that could work for you.

**Comment by niloc132** [comment]
Very nice @ronshapiro - I'll take a deeper look soon, but at least at a glance it seems that there is on reason it couldn't apply to repos other than central (contrary to the commit message)? Looking forward to giving this a shot, thanks!

**Comment by ronshapiro** [comment]
Ah yeah, that's just the most common but a pom is a pom. Would be great to hear any questions you have from how it's documented or any quirks you run into

**Comment by realityforge** [comment]
Closing this as no longer relevant as POMs are checked in.
