### ISSUE TITLE
Proposals for new artifacts

### ISSUE THREAD

**Issue by realityforge** [google/elemental2#47]
Would this project consider accepting pull requests for additional artifacts? Is this on a case-by-case basis or is anything that is available as externs in the closure-compiler project a candidate. In particular I am interested in:

* An `elemental2-webassembly` artifact based off `@com_google_closure_compiler//:contrib/externs/webassembly.js`. We have produced a jar for this and it seems to be reasonable - or at least we have not run into any issues yet.
* An `elemental2-webcrypto` artifact based off `@com_google_closure_compiler//:externs/browser/w3c_webcrypto.js`. (We have yet to try this but it would be fun to play with.

Thoughts? Do they live in elemental2 or should they live elsewhere?

**Comment by niloc132** [comment]
I'm also interested in (and interested in adding) a jar for the new [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) types.

**Comment by vegegoku** [comment]
I also would like to see more externs get included, and **Intl** in specific

**Comment by jDramaix** [comment]
I think webcrypto and Intl are definitely good candidates. Webassembly could be part of elemental as well as the spec is driven by w3c but I need to think more about that

**Comment by realityforge** [comment]
Webassembly artifact submitted as https://github.com/google/elemental2/pull/66

**Comment by realityforge** [comment]
WebAssembly artefact now merged. Huzzah.

**Comment by realityforge** [comment]
`elemental2-webcrypto` is no longer on my radar so I will close this issue until the need arises.
