### ISSUE TITLE
Document.window.getSelection is missing from DomGlobal.window

### ISSUE THREAD

**Issue by payammeyer** [google/elemental2#58]
the `getSelection` method is missing from `DomGlobal.window`. It would be very nice to add it, in the meantime, I've been using the following workaround as generously suggested by @niloc132.

```java
@JsMethod(name="getSelection", namespace=JsPackage.GLOBAL)
public static native Selection getSelection();
```

**Comment by jDramaix** [comment]
Will be fixed by fixing #86
