### ISSUE TITLE
Lack of any SVG Documentation (or examples)?

### ISSUE THREAD

**Issue by dfht** [google/elemental2#62]
Help!
I can't find any documentation anywhere about how to use SVG in Elemental 2.
All my attempts at 'guessing' what methods to use result in ClasCastException or TypeError (e.g. createSVGLength is not a function etc.).
There appears to be an SVGDocument class, but I have no idea how to access the instance. 
Just a simple example to get started would suffice.

**Comment by dfht** [comment]
And I'm interested in inline svg elements (so HTMLDocument as the root) so I guess the SVGDocument doesn't come into it after all...
I use the document.createElement("svg")  but get ClassCastException when trying to cast to SVGSVGElement.
I tried the hack of Js.uncheckedCast to get around this, but just ran into further issues when trying to set the length.
For example, SVGSVGElement.createSVGLength is apparently 'not a function', but if I try new SVGLength() then I also get an error, and hence I cannot seem to set the sizing attributes of any of the SVG elements.

I just cannot see how I am supposed to use this library at present (maybe it's just not usable yet?)....

**Comment by dfht** [comment]
Some progress....

I realized that I need to create SVG elements via the createElementNS rather than createElement!
Maybe that will be enough to get me going.... 


`String SVG_NAMESPACE_URI = "http://www.w3.org/2000/svg";
		SVGSVGElement svg = (SVGSVGElement) document.createElementNS(SVG_NAMESPACE_URI, "svg");`


I'm not really used to using native JS for SVG stuff, but am trying to replace a dependency on a third party GWT library with my own coding using Elemental 2, so I'm just feeling my way at present :).

**Comment by niloc132** [comment]
Yeah, elemental2 is a perfect fit for cases where you are translating plain JS - for other cases where some abstraction/simplification/boilerplate is needed like this, some kind of a wrapper would probably be ideal. You've found the correct way to create the various `svg:*` elements - the `uncheckedCast` will not be necessary now (since previously the browser wasn't even creating the correct element), and createSVGLength() should now behave properly as well.

**Comment by vegegoku** [comment]
@dfht 
I sue SVG [here](https://github.com/DominoKit/domino-ui/blob/master/src/main/java/org/dominokit/domino/ui/timepicker/TimePicker.java) this was my first attempt to use SVG and MDN helped me a lot.

**Comment by dfht** [comment]
Thanks guys. I'm making good progress now. It was the initial creation of elements that I was missing, but now it seems like I will be able to achieve what I want....

**Comment by niloc132** [comment]
Can you close the issue?

**Comment by dfht** [comment]
Yes, sure....
