### ISSUE TITLE
JsIterator interface apparently permits Java code to implement two methods with the same name

### ISSUE THREAD

**Issue by niloc132** [google/elemental2#63]
```
@JsType(isNative = true, name = "Iterator", namespace = JsPackage.GLOBAL)
public interface JsIterator<VALUE> {
  JsIIterableResult<VALUE> next();

  JsIIterableResult<VALUE> next(VALUE p0);
}
```
Attempting to implement this results in runtime confusion, as the Java type is attempting to export two different `function`s, both with the same name "next". Here from just wrapping a plain iterator - returning `null` for the `next(val0)`, and roughly this code for the `next()` method:
```
JsIIterableResult<SomeObject> val = JsIIterableResult.create();
if (iterator.hasNext()) {
  val.setValue(iterator.next());
}
val.setDone(!iterator.hasNext());
return val;
```

```
cggl.MyIterator_classLit = createForClass('my.pack.age', 'MyIterator', 355);
mp.MyIterator = function MyIterator(val$iterator){
  this.val$iterator2 = val$iterator;
}
;
defineClass(356, 1, {}, mp.MyIterator);
_.next = function next_1(p0){
  return castTo(p0, 59) , null;
}
;
_.next = function next_0(){
  var val;
  val = jb.emptyObjectLiteral();
  ju.$hasNext_8(this.val$iterator2) && (val.value = ju.$next(this.val$iterator2));
  val.done = !ju.$hasNext_8(this.val$iterator2);
  return val;
}
;
```

It isn't clear how the developer can know that this cannot be implemented by their own Java (aside from the "try-it-and-fail" approach), in contrast with EventInit, JsIterableResult and other interfaces. It looks like perhaps several bugs coming together, but at least for elemental2, the `next(val)` method could be removed. It doesn't appear to be a part of the spec except in a "sure, I guess you could do that, but we're not defining it" sort of way https://www.ecma-international.org/ecma-262/6.0/#sec-iteration, suggesting that the specifying the type (or count) of the argument in the interface may not be necessarily correct.

> Arguments may be passed to the next function but their interpretation and validity is dependent upon the target Iterator.

**Comment by gkdn** [comment]
There is a way to implement it. Not sure where we documented that but I know we intended to document that at least :)

But before any of that, this something enforced by restriction checking and  should be a compile error so you should file a GWT bug (and maybe try to send a patch).

**Comment by jDramaix** [comment]
Hi @niloc132 Did you fill a GWT bug as suggested by @gkdn ?

**Comment by niloc132** [comment]
Sorry, making my way through lots of old bugs that I haven't followed up on. I will file a bug against gwtproject/gwt about the restriction checker failing to enforce, and then someone can describe how one would get around this? Best I can come up with is making your own @JsFunction and casting to this one, but that seems silly.

**Comment by rluble** [comment]
So to implement it you need to choose one of the methods (the more general of the two) to implement in the subclass.

````java
class MyJsIterator<X> implements JsIterator<X> {

   JsIterableResult<X> next(X p0) {
      if (p0 == null) {
          // here would be a call without the parameter (also when called with null)
     }
  }
}
```

When there are NATIVE overloads you can only implement one of the types in the subclass. You might have any number of native overloads as long as there is only one method with a body.

**Comment by rluble** [comment]
This is not a bug in elemental, but rather it is probably a bug in GWT. It should work fine in J2CL. If it does not work in J2CL file a bug there.

**Comment by niloc132** [comment]
Sorry, meant to get this sent off last night, but I couldn't work out the actual failure in time - I had erroneously been making the implementation bind T as Object, which does not result in a failure. Now that I understand what is happening, I'll see if I can work out a fix this evening.

Thanks for the workaround @rluble!
