### ISSUE TITLE
Missing setSelectionRange

### ISSUE THREAD

**Issue by andreaselias** [google/elemental2#69]
HTMLInputElement should also have setSelectionRange function.

**Comment by tbroyer** [comment]
Also `selectionStart`, `selectionEnd`, `selectionDirection`, `setRangeText` (maybe others); see https://html.spec.whatwg.org/multipage/input.html#the-input-element:concept-element-dom

**Comment by jDramaix** [comment]
Needs #86 to be fixed.

External contribution is welcome
