### ISSUE TITLE
Instantiating elemental2.dom.RequestInit

### ISSUE THREAD

**Issue by dharezlak** [google/elemental2#7]
This is a question but potentially an issue. How should I instantiate the `elemental2.dom.RequestInit` type to pass it on the the `elemental2.dom.Window.fetch(String, RequestInit)` method? Shouldn't there be some kind of a builder available to easily construct such types?

**Comment by tbroyer** [comment]
See https://github.com/google/elemental2/issues/6#issuecomment-317632360

For now, I _suppose_ (not tested) you can implement the interface and pass an instance of your class (and no need to make it a `@JsType` AFAICT)

**Comment by jDramaix** [comment]
there is now a static factory method for each dictionary type: `RequestInit.create()`
