### ISSUE TITLE
CanvasRenderingContext2D missing imageSmoothingEnabled

### ISSUE THREAD

**Issue by mdproctor** [google/elemental2#73]
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled

**Comment by realityforge** [comment]
This has been added to closure compiler externs and will be available in the next release of elemental2. Until then you can download the latest elemental version via:

```xml
    <dependency>
      <groupId>org.realityforge.com.google.elemental2</groupId>
      <artifactId>elemental2-dom</artifactId>
      <version>1.0.0-b19-fb227e3</version>
    </dependency>
```

**Comment by jDramaix** [comment]
Thanks

**Comment by niloc132** [comment]
Just double checking - is this fixed now in the upstream "google/elemental2", or is it being closed as "won't fix, since another fork has it"?

**Comment by realityforge** [comment]
It is fixed in the closure-compiler project ... and thus transitively here as well.

**Comment by niloc132** [comment]
Excellent, thanks.
