### ISSUE TITLE
Cam'

### ISSUE THREAD

**Issue by solomatov** [google/elemental2#74]

**Comment by solomatov** [comment]
I have the following error: target '@com_google_elemental2//java/elemental2/core:core' is not visible from target XYZ. Check the visibility declaration of the former target if you think the dependency is legitimate

**Comment by jDramaix** [comment]
you have to use @com_google_elemental2//:elemental2-core

I'm close to have elemental2 working with bazel and j2cl. I'll update the README when it's done

**Comment by solomatov** [comment]
@jDramaix That's great news! Thank you!
