### ISSUE TITLE
Cannot access int[] from Uint8ClampedArray

### ISSUE THREAD

**Issue by mdproctor** [google/elemental2#75]
I'm trying to get direct access to the Uint8ClampedArray array, returned from an ImageData instance. It throws a ClassCastException. Is this a bug, am I doing something wrong, or maybe  misunderstanding the API?
      Uint8ClampedArray.ConstructorLengthUnionType temp = Uint8ClampedArray.ConstructorLengthUnionType.of(dataArray);
        int[] data = temp.asIntArray();

**Comment by mdproctor** [comment]
For now I'm just doing:
int[] data = Js.uncheckedCast(dataArray);

And it works, but it makes me think there is a bug, if I cannot asIntArray via the main type safe api.

**Comment by niloc132** [comment]
This may be the same design issue in jsinterop-generator (or jsinterop itself?) as https://github.com/google/elemental2/issues/28?

**Comment by gkdn** [comment]
Related to https://github.com/google/elemental2/issues/28
