### ISSUE TITLE
Typed Arrays should have an overloaded from method or constructor that takes an Array

### ISSUE THREAD

**Issue by tbenbrahim** [google/elemental2#8]
JavaScript code, typically with arrays with thousands of elements, that I am trying to emulate with Elemental2:
```
var f=new Float32Array(JSON.parse("[1.1, 2.3, 4.5, 8]"));
f
Float32Array(4) [1.100000023841858, 2.299999952316284, 4.5, 8]
```
I have not found a way to coerce a JavaScript Array of Numbers returned from JSON parse to a double[],. You can of course create a new array and copy the Array elements into the double[] one by one, but that is not the point.
Having all typed Arrays accept an Array would solve this problem.

**Comment by jDramaix** [comment]
Typed arrays accept only an array of number. Adding a overload accepting an Array of Object will weaken the type checking.

If you are sure the array returned by JSON.parse is an array of double you can use Js.cast (from jsinterop-base) to cast to double[]
