### ISSUE TITLE
Returning values from EventListener

### ISSUE THREAD

**Issue by anbuck** [google/elemental2#84]
Javascript allows event handlers to return a value. For example, in the dragstart event, the event handler should return false to prevent a drag. However, Elemental2 defines the handleEvent() method of EventListener as having a void return value.

Since most event handlers don't need to return a value, I understand why the handleEvent() method is defined with a void return type, but we need a way to return a value when necessary.

**Comment by tbroyer** [comment]
AFAICT you should use `event.preventDefault()`.

**Comment by anbuck** [comment]
Ok, thanks. That seems to work.
