### ISSUE TITLE
Add w3c_elementtraversal.js to elemental2-dom

### ISSUE THREAD

**Issue by jDramaix** [google/elemental2#87]
**Contribution is welcome here.**

This can be fixed by 
 - adding [google/closure-compiler/blob/master/externs/browser/w3c_elementtraversal.js](https://github.com/google/closure-compiler/blob/master/externs/browser/w3c_elementtraversal.js) to [elemental2-dom](https://github.com/google/elemental2/blob/master/java/elemental2/dom/BUILD#L112)
 - Follow the procedure explained in [Contribution document](https://github.com/google/elemental2/blob/master/CONTRIBUTING.md#adding-a-missing-javascript-api)

**Comment by realityforge** [comment]
This has already occurred and the issue can be closed. It seems that the closure extern definition for children is slightly incorrect but this can be addressed in that repository
