### ISSUE TITLE
Add webkit_dom.js to elemental2-dom

### ISSUE THREAD

**Issue by jDramaix** [google/elemental2#88]
**Contribution is welcome here.**

This can be fixed by 
 - adding [google/closure-compiler/blob/master/externs/browser/webkit_dom.js](https://github.com/google/closure-compiler/blob/master/externs/browser/webkit_dom.js) to [elemental2-dom](https://github.com/google/elemental2/blob/master/java/elemental2/dom/BUILD#L103)
 - Follow the procedure explained in [Contribution document](https://github.com/google/elemental2/blob/master/CONTRIBUTING.md#adding-a-missing-javascript-api)

**Comment by realityforge** [comment]
I will try to tackle this over the next little bit. It looks like it needs some surgery in the upstream closure externs to get working so it may take a bit of time to get through.

**Comment by realityforge** [comment]
Feel free to assign to me ... or it may not be possible for non project members - or at least I can't seem to do it ;)

**Comment by jDramaix** [comment]
You should be able to assign yourself now.

Thanks for the help!

**Comment by realityforge** [comment]
Thanks ... but it looks like I can now be assigned issues according to [1] but only people with write access seem to be able to assign issues according to [2]. Feel free to assign me if you want.

Anyhoo - I mainly just wanted to indicate that this may take some time to work through and to avoid anyone else doing the same work ... which all these comments have probably achieved the same goal.

[1] https://api.github.com/repos/google/elemental2/assignees
[2] https://help.github.com/en/articles/assigning-issues-and-pull-requests-to-other-github-users

**Comment by realityforge** [comment]
It seems that the only part left in `webkit_dom.js` that we are likely to want to support (i.e. exists in other browsers like chrome)  is [Selection](https://w3c.github.io/selection-api/#selection-interface) which hopefully I will get to in the next week or two.

**Comment by jDramaix** [comment]
Thanks for the huge work Peter! Really appreciated!

**Comment by realityforge** [comment]
Getting close to fixing this. #117 moves selection API into a separate top level extern. However it still seems we need to move a few more properties around (i.e. `Window.prototype.devicePixelRatio` from CSSOM among others)

**Comment by realityforge** [comment]
Making `Window.prototype.devicePixelRatio` available to Elemental2 (as well as a few other methods from the cssom-view spec) has been submitted upstream as google/closure-compiler#3395

Once this and google/closure-compiler#3370 has merged we can probably close this issue as the remaining externs are not standardized.

**Comment by realityforge** [comment]
The one remaining symbol that we may want access to from `webkit_dom.js` is `Element.prototype.scrollIntoViewIfNeeded` It is not standardized but in a few weeks it will be all the evergreen browsers except Firefox and not in IE11. See https://caniuse.com/#feat=scrollintoviewifneeded

Most of the applications I have built recently use this symbol but we use a local jsinterop method to do so. I am inclined to leave this out of Elemental2 but I can also see an argument for including it given that it is reasonably broadly supported. Any opinions?

If we don't want this in Elemental2 then I think this issue can be closed

**Comment by jDramaix** [comment]
IE is not really a problem but Firefox is a bigger issue. It does seem this api will be implemented in Firefox soon.  You can open a specific bug for that and we will discuss there but for now I'll close this one.

Thanks for your huge work on this!
